_wandb:
    value:
        cli_version: 0.23.1
        e:
            epvq38pgqpzg23ccqjdj3yvdvknws5j3:
                args:
                    - -r
                    - "2"
                    - -n
                    - "2"
                codePath: mochi\main.py
                codePathLocal: main.py
                email: yukis-34@yahoo.ne.jp
                executable: C:\Users\yukis\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 4a32bc6c1ea88daa3cb7851acd077384af6b8aac
                    remote: https://github.com/fkun314/penguin-paper.git
                host: DESKTOP-QHJR8EO
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\yukis\Documents\penguin-paper\mochi\main.py
                python: CPython 3.10.11
                root: C:\Users\yukis\Documents\penguin-paper\mochi
                startedAt: "2025-12-12T11:20:41.126659Z"
                writerId: epvq38pgqpzg23ccqjdj3yvdvknws5j3
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.11
            "5": 0.23.1
            "6": 4.55.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.23.1
            "13": windows-amd64
api_provider:
    value: null
applicant_model_name:
    value: gpt-4o-mini
experiment_id:
    value: random_api_gpt_4o_mini_r2_d850d108
interviewer_model_name:
    value: gpt-4o-mini
interviewer_model_type:
    value: api
max_rounds:
    value: 2
set_index:
    value: 13
simulation_num:
    value: 2
