_wandb:
    value:
        cli_version: 0.23.0
        e:
            phg9gs11yjf389l4l6bosviofu7f6a74:
                args:
                    - -t
                    - local
                    - -m
                    - SWALLOW
                    - -n
                    - "100"
                codePath: mochi/main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "16808312832"
                        used: "1409335296"
                email: fkun314@gmail.com
                executable: /host/data/space9/fujita-h/penguin-paper/.venv/bin/python
                git:
                    commit: bb0149a454a429cd0280898fb30ad61f309f1f9d
                    remote: https://github.com/fkun314/penguin-paper
                gpu: NVIDIA RTX A4000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-c774eed3-9e80-2f28-823f-43e44e2281f8
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-33386d84-af50-6144-e150-f3ff292a9fc2
                host: gp10.cs.uec.ac.jp
                memory:
                    total: "33616625664"
                os: Linux-5.4.0-40-generic-x86_64-with-glibc2.31
                program: /host/home/yanai-lab/Sotsuken24/fujita-h/penguin-paper/mochi/main.py
                python: CPython 3.10.18
                root: /host/home/yanai-lab/Sotsuken24/fujita-h/penguin-paper/mochi
                startedAt: "2025-12-04T17:27:07.072948Z"
                writerId: phg9gs11yjf389l4l6bosviofu7f6a74
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.18
            "5": 0.23.0
            "6": 4.57.1
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
candidate_preparations:
    value:
        - low
        - medium
        - high
company_name:
    value: クラウドリンク株式会社
interviewer_model_name:
    value: SWALLOW
interviewer_model_type:
    value: local
max_rounds:
    value: 20
num_candidates:
    value: 3
set_index:
    value: 0
simulation_num:
    value: 90
