_wandb:
    value:
        cli_version: 0.23.1
        e:
            brndu9bfo4apt9ickutmb4mtg1lnrerx:
                args:
                    - -n
                    - "80"
                    - -r
                    - "11"
                codePath: mochi\main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1997960900608"
                        used: "1067871682560"
                email: yukis-34@yahoo.ne.jp
                executable: C:\Users\yukis\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 2d13bab10371863f223ae00f6486aa82e623f6b9
                    remote: https://github.com/fkun314/penguin-paper.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-9545a7d1-0229-538d-0aec-37d11ee07772
                host: DESKTOP-QHJR8EO
                memory:
                    total: "137279569920"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\yukis\Documents\penguin-paper\mochi\main.py
                python: CPython 3.10.11
                root: C:\Users\yukis\Documents\penguin-paper\mochi
                startedAt: "2025-12-13T21:15:56.505185Z"
                writerId: brndu9bfo4apt9ickutmb4mtg1lnrerx
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.11
            "5": 0.23.1
            "6": 4.55.0
            "8":
                - 3
            "10":
                - 20
            "12": 0.23.1
            "13": windows-amd64
api_provider:
    value: null
applicant_model_name:
    value: gpt-4o-mini
experiment_id:
    value: random_api_gpt_4o_mini_r11_4590aaa0
interviewer_model_name:
    value: gpt-4o-mini
interviewer_model_type:
    value: api
max_rounds:
    value: 8
set_index:
    value: 11
simulation_num:
    value: 74
