_wandb:
    value:
        cli_version: 0.23.0
        e:
            6zytbw3cf6zcihafkpy3ixs2y3tld6nx:
                args:
                    - -t
                    - local
                    - -m
                    - qwen2.5-7b-instruct
                codePath: mochi\main.py
                codePathLocal: mochi\main.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "3000574668800"
                        used: "2515408035840"
                email: fkun314@gmail.com
                executable: D:\GitHub\penguin-paper\.venv\Scripts\python.exe
                git:
                    commit: 9fa94bfe0ed03f90b926c5260f2a3476d23ea4c1
                    remote: https://github.com/fkun314/penguin-paper.git
                gpu: NVIDIA GeForce RTX 3080 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10240
                      memoryTotal: "12884901888"
                      name: NVIDIA GeForce RTX 3080 Ti
                      uuid: GPU-2dff6adf-f8d8-7e07-d038-6a78f7660d8b
                host: i9-7
                memory:
                    total: "68537458688"
                os: Windows-10-10.0.26100-SP0
                program: D:\GitHub\penguin-paper\mochi\main.py
                python: CPython 3.10.19
                root: D:\GitHub\penguin-paper
                startedAt: "2025-12-02T05:43:36.803181Z"
                writerId: 6zytbw3cf6zcihafkpy3ixs2y3tld6nx
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 95
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.57.3
            "8":
                - 3
            "10":
                - 20
            "12": 0.23.0
            "13": windows-amd64
candidate_preparations:
    value:
        - high
        - medium
        - low
company_name:
    value: 株式会社デジタルブック
interviewer_model_name:
    value: qwen2.5-7b-instruct
interviewer_model_type:
    value: local
max_rounds:
    value: 20
num_candidates:
    value: 3
set_index:
    value: 22
simulation_num:
    value: 1
