_wandb:
    value:
        cli_version: 0.23.0
        e:
            gupdmoahxyf5qbi5gabf3sdjejwu7d5m:
                args:
                    - -t
                    - local
                    - -m
                    - qwen2.5-7b-instruct
                    - -n
                    - "100"
                codePath: mochi/main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.0"
                disk:
                    /:
                        total: "33703247872"
                        used: "1476198400"
                email: fkun314@gmail.com
                executable: /host/data/space9/fujita-h/penguin-paper/.venv/bin/python
                git:
                    commit: bb0149a454a429cd0280898fb30ad61f309f1f9d
                    remote: https://github.com/fkun314/penguin-paper
                gpu: NVIDIA RTX A4000
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-57e59a39-484e-4cba-cded-4cc79e036779
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-0203b299-6e72-2a46-2522-628b2e58ac1d
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-5e4f30fd-f7be-46f9-0d55-19e05967fbe4
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17171480576"
                      name: NVIDIA RTX A4000
                      uuid: GPU-b2787fec-8dc5-1390-463d-6bd02e4b3d63
                host: gp24.cs.uec.ac.jp
                memory:
                    total: "67406495744"
                os: Linux-5.4.0-40-generic-x86_64-with-glibc2.31
                program: /host/home/yanai-lab/Sotsuken24/fujita-h/penguin-paper/mochi/main.py
                python: CPython 3.10.18
                root: /host/home/yanai-lab/Sotsuken24/fujita-h/penguin-paper/mochi
                startedAt: "2025-12-04T08:38:23.710229Z"
                writerId: gupdmoahxyf5qbi5gabf3sdjejwu7d5m
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 95
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 71
                - 95
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.18
            "5": 0.23.0
            "6": 4.57.1
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
candidate_preparations:
    value:
        - medium
        - high
        - low
company_name:
    value: 株式会社スマートフィンテック
interviewer_model_name:
    value: qwen2.5-7b-instruct
interviewer_model_type:
    value: local
max_rounds:
    value: 20
num_candidates:
    value: 3
set_index:
    value: 38
simulation_num:
    value: 97
